### Server ###
server:
  port: 9000

### Spring ###
spring:

  ### Application ###
  application:
    name: auth-server

  ### JPA ###
  jpa:
    show-sql: on
    open-in-view: off

  ### Datasource ###
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5440/person_db

### Logging ###
logging:
  level:
    root: info

### Core ###
core:
  jks:
    directory-path: jwt-certificate/demo/
