### Server ###
server:
  port: 9000

### Spring ###
spring:

  ### Application ###
  application:
    name: auth-server

### Logging ###
logging:
  level:
    root: info

### Core ###
core:
  jks:
    directory-path: jwt-certificate/demo/
