### Server ###
server:
  port: 9002

### Spring ###
spring:

  ### Application ###
  application:
    name: person-service

  ### JPA ###
  jpa:
    show-sql: true
    open-in-view: off

  ### Datasource ###
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5440/person_db

### Logging ###
logging:
  level:
    root: info
