### Server ###
server:
  port: 9002
  servlet:
    context-path: /person-service

### Spring ###
spring:

  ### Application ###
  application:
    name: person-service

  ### JPA ###
  jpa:
    show-sql: true
    open-in-view: off

  ### Datasource ###
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5440/person_db

  ### OAuth2 ###
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  ### Flyway ###
  flyway:
    installed-by: Serhey Doroshenko

### Logging ###
logging:
  level:
    root: info
