### Server ###
server:
  port: 9001

### Spring ###
spring:

  ### Application ###
  application:
    name: person-service

  ### Datasource ###
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5440/person_db

### Eureka ###
eureka:
  client:
    service-url:
      defaultZone: "http://user:1111@localhost:8761/eureka/"

### Logging ###
logging:
  level:
    root: info
