### Server ###
server:
  port: 9001

### Spring ###
spring:

  ### Application ###
  application:
    name: person-service

  ### Profile ###
  config:
    activate:
      on-profile: default

### Eureka ###
eureka:
  client:
    service-url:
      defaultZone: "http://user:1111@localhost:8761/eureka/"